repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending

  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: v4.3.21
  #   hooks:
  #     - id: isort

  - repo: local
    hooks:
      - id: make-lint
        name: Lint files
        language: system
        entry: make lint
