repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
      - id: seed-isort-config

  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: v4.3.21
  #   hooks:
  #     - id: isort

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: make-lint
        name: Lint files
        language: system
        entry: make lint
      - id: make-fmt
        name: Format files
        language: system
        entry: make fmt
